### ISSUE TITLE
Can not compile php: undefined reference to `SSL_library_init'

### ISSUE THREAD

**Issue by izumeroot** [fpoirotte/phpfarm#12]
Hello! In Kubuntu 14 I can not compile php
After command sudo ./compile.sh 5.3.29
I have log with

```
t  -o sapi/cgi/php-cgi
ext/openssl/openssl.o: In function `zm_startup_openssl':
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:992: undefined reference to `SSL_library_init'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:993: undefined reference to `OpenSSL_add_all_ciphers'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:994: undefined reference to `OpenSSL_add_all_digests'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:995: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:997: undefined reference to `ERR_load_ERR_strings'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:998: undefined reference to `ERR_load_crypto_strings'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:999: undefined reference to `ERR_load_EVP_strings'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:1003: undefined reference to `SSL_get_ex_new_index'
/opt/phpfarm/src/php-5.3.29/ext/openssl/openssl.c:1078: undefined reference to `X509_get_default_cert_area'
ext/openssl/openssl.o: In function `zm_info_openssl':
```

How can I fix it?

I use this article http://www.jabommi.de/wiki/downgrade-php-5-5-to-5-3-ubuntu-14-with-multiple-php-versions/

Thank you

**Comment by izumeroot** [comment]
May be I can not compile php 5.3.29 if I have php 5.3.10 (and dependent libs) installed from Ubuntu repo? May be I need upgrade php (and dependent libs) from repo?

**Comment by fpoirotte** [comment]
Sorry for the late reply, I've been busy with work.
Could you please paste the contents of src/php-5.3.29-debug/config.nice ?

Also, make sure the following packages are installed on your system: libssl1.0.0, libssl-dev. If not, install these then try compiling again.

**Comment by izumeroot** [comment]
Sorry I have removed it already

**Comment by izumeroot** [comment]
But it is may be  because i have php 5.3.10 installed from repo?

**Comment by fpoirotte** [comment]
No, phpfarm only needs the proper headers (= -dev packages) and libraries to compile and run.
For example, I have PHP 5.6.12 installed here from the official Debian repositories, but I also manage 12 others versions of PHP with phpfarm in parallel.

Anyway, I'll leave it up to you whether you want to give it another try or whether I should just close this issue.

**Comment by izumeroot** [comment]
I think, i I have downgraded php version, I have downgraded dev packages also.
I will do another try.

**Comment by izumeroot** [comment]
http://pastebin.com/sZK28jwT

**Comment by MarioLipinski** [comment]
Passing `--with-libdir=lib/x86_64-linux-gnu` to configure did the trick for me. However, this would break the build for some modules like imap, I guess because of missing multiarch support.

**Comment by fpoirotte** [comment]
@izumeroot: did you manage to fix the issue?

FWIW, some PHP extensions use hard-coded locations or expect the location of libraries and headers to differ only by their last directory (eg. "/usr/local/include" & "/usr/local/lib"), while on a multiarch system, these directories may be further split (eg. "/usr/local/include" & "/usr/local/lib/x86_64-linux-gnu"). Those extensions will indeed break. Also, most extensions do not rely pkgconfig to locate those directories.

Using --with-libdir or some configure options, you may be able to trick PHP into looking for libraries/header files in a different directory, but expect other extensions to fail to build as a side-effect (see Mario's comment above).

The results also vary depending on what PHP version you're trying to build. Newer releases tend to fix multiarch compatibility issues. If possible, I suggest you try building a newer release.

**Comment by izumeroot** [comment]
@fpoirotte Hello!

My error was because i have php 5.3.10 (dev packages) installed when I tried compile php 5.3.29.  
I have downgraded php version (dev packages also) before using phpfarm.

**Comment by fpoirotte** [comment]
Closing based on previous comment.
