### ISSUE TITLE
pear.php.net security branch and tainted go-pear.phar

### ISSUE THREAD

**Issue by fpoirotte** [fpoirotte/phpfarm#25]
The folks in charge of pear.php.net reported that due to a security breach, the the official PEAR website (pear.php.net) has been serving a tainted version of the ``go-pear.phar`` archive for about 6 months now (see https://twitter.com/pear/status/1086634389465956352 for more information).

phpfarm does not install PEAR by default, and even when specifically asked to install PEAR, it does so without relying on the ``go-pear.phar`` (instead relying on the ``install-pear-nozlib.phar`` archive instead). However, it is unknown whether the archive used by phpfarm was also affected or not.

The PEAR team has released new (known good) versions of their various archives. They also provided GPG signatures for the new archives.
Users of phpfarm are advised to replace their local copy of the ``install-pear-nozlib.phar`` archive with the one provided in this repository: https://github.com/pear/pearweb_phars.

To replace your local copy, open a shell and go to phpfarm's root folder, then apply the following steps:
```
# Navigate to where the archive gets downloaded
cd src/bzips

# Delete the archive
rm -f install-pear-nozlib.phar

# Download the new archive and its signature
wget https://github.com/pear/pearweb_phars/raw/master/install-pear-nozlib.phar https://github.com/pear/pearweb_phars/raw/master/install-pear-nozlib.sig
``` 

The new release has been signed by Chuck Burgess's (@ashnazg) and can be checked using gpg. Fingerprint for the GPG key : 0x72a321bac245f175

**Comment by ashnazg** [comment]
`install-pear-nozlib.phar` has not shown any tampering... only `go-pear.phar`. So phpfarm should be fine.

Note these recent threads:
https://twitter.com/pear/status/1088155252644372482
https://twitter.com/pear/status/1088194973202288640

**Comment by fpoirotte** [comment]
Thanks for clarifying things up.
